[package]
name = "fluxline-hm"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["robin <@Lopfi>"]
license = "MIT"
description = "Unofficial Bachelor's thesis template for Munich University of Applied Sciences (Hochschule München)"
repository = "https://github.com/Lopfi/fluxline-hm"
keywords = [""]
categories = ["thesis"]
disciplines = ["engineering"]
exclude = [".devcontainer/", ".vscode/"]

[template]
path = "template"
entrypoint = "main.typ"

thumbnail = "main.png"
